import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { test, expect, type Page } from "@playwright/test";
import {
  FORBIDDEN_ON_TERRITORY_SURFACES,
  FORBIDDEN_PATTERNS,
  PUBLIC_ROUTES_TO_SCAN,
  RULE_LABEL,
  isSeoPackagesRoute,
  type Severity,
} from "../src/config/pricing";

// Whole-site sweep. Fails the build if any public route (other than
// the allowlisted SEO Packages routes in src/config/pricing.ts) leaks
// the removed Bullets/Boom/Bombs block or the $85/$285/$585 one-time
// prices. On failure, writes a diagnostic artifact under
// `pricing-guard-report/` with each URL, the exact matched text, and
// element + full-page screenshots of the offending region.
//
// The forbidden strings, regex patterns, allowed routes, and route
// list are ALL defined in src/config/pricing.ts — this spec has no
// pricing knowledge of its own.

const REPORT_DIR = join(process.cwd(), "pricing-guard-report");
const REPORT_JSON = join(REPORT_DIR, "report.json");
const REPORT_MD = join(REPORT_DIR, "report.md");
const SITEMAP_PATH = join(process.cwd(), "public", "sitemap.xml");

/**
 * Parse `public/sitemap.xml` (generated by scripts/generate-sitemap.ts
 * on every publish) and return the path portion of every entry. Falls
 * back to an empty list if the sitemap is missing or malformed, so
 * CI never dies on a bad sitemap — the static PUBLIC_ROUTES_TO_SCAN
 * list still runs.
 */
function readSitemapRoutes(): string[] {
  if (!existsSync(SITEMAP_PATH)) return [];
  try {
    const xml = readFileSync(SITEMAP_PATH, "utf8");
    const locs = Array.from(xml.matchAll(/<loc>([^<]+)<\/loc>/g), (m) => m[1]);
    const paths = new Set<string>();
    for (const loc of locs) {
      try {
        const u = new URL(loc);
        // Skip binary/static assets and anchors.
        if (/\.(xml|png|jpg|jpeg|webp|svg|pdf|zip)$/i.test(u.pathname)) continue;
        paths.add(u.pathname.replace(/\/+$/, "") || "/");
      } catch {
        /* not a URL — skip */
      }
    }
    return [...paths];
  } catch {
    return [];
  }
}

const SITEMAP_ROUTES = readSitemapRoutes();
const ROUTES_TO_SCAN = Array.from(
  new Set<string>([...PUBLIC_ROUTES_TO_SCAN, ...SITEMAP_ROUTES]),
);

type Match = {
  kind: "substring" | "regex";
  name: string;
  severity: Severity;
  matchedText: string;
  contextBefore: string;
  contextAfter: string;
  fullPageScreenshot: string;
  snippetScreenshot: string | null;
  annotatedScreenshot: string | null;
};

type RouteReport = {
  route: string;
  url: string;
  status: number | null;
  scanned: boolean;
  skippedReason?: string;
  matches: Match[];
  discoveredVia: "static" | "sitemap" | "both";
};

function ensureReportDir() {
  if (!existsSync(REPORT_DIR)) mkdirSync(REPORT_DIR, { recursive: true });
}

function context(text: string, index: number, len: number) {
  const before = text.slice(Math.max(0, index - 60), index);
  const after = text.slice(index + len, index + len + 60);
  return { contextBefore: before, contextAfter: after };
}

// Accumulate one report per test run.
const runReport: RouteReport[] = [];

test.beforeAll(() => {
  ensureReportDir();
  // Reset report on first run.
  writeFileSync(REPORT_JSON, JSON.stringify({ generatedAt: null, routes: [] }, null, 2));
});

test.afterAll(() => {
  const anyFailed = runReport.some((r) =>
    r.matches.some((m) => m.severity === "fail"),
  );
  const anyWarned = runReport.some((r) =>
    r.matches.some((m) => m.severity === "warn"),
  );
  writeFileSync(
    REPORT_JSON,
    JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        ok: !anyFailed,
        anyWarned,
        sitemapRoutesFound: SITEMAP_ROUTES.length,
        totalRoutesScanned: ROUTES_TO_SCAN.length,
        routes: runReport,
      },
      null,
      2,
    ),
  );
  const md: string[] = [];
  md.push(`# Pricing guard report`);
  md.push(``);
  md.push(`- Overall: ${anyFailed ? "❌ FAIL" : anyWarned ? "⚠️  PASS (with warnings)" : "✅ PASS"}`);
  md.push(`- Routes scanned: ${runReport.filter((r) => r.scanned).length}`);
  md.push(`- Routes discovered via sitemap: ${SITEMAP_ROUTES.length}`);
  md.push(`- Routes skipped (SEO Packages allowlist): ${runReport.filter((r) => !r.scanned).length}`);
  md.push(``);
  for (const r of runReport) {
    if (r.matches.length === 0) continue;
    const fail = r.matches.some((m) => m.severity === "fail");
    md.push(`## ${fail ? "❌" : "⚠️ "} ${r.route}`);
    md.push(``);
    md.push(`URL: \`${r.url}\``);
    md.push(``);
    for (const m of r.matches) {
      md.push(`- **[${m.severity}][${m.kind}] ${m.name}** matched \`${m.matchedText}\``);
      md.push(`  - context: …${m.contextBefore}**${m.matchedText}**${m.contextAfter}…`);
      md.push(`  - full-page screenshot: \`${m.fullPageScreenshot}\``);
      if (m.snippetScreenshot) md.push(`  - snippet screenshot: \`${m.snippetScreenshot}\``);
      if (m.annotatedScreenshot) md.push(`  - annotated overlay: \`${m.annotatedScreenshot}\``);
    }
    md.push(``);
  }
  writeFileSync(REPORT_MD, md.join("\n"));
});

/**
 * In-page highlighter: draws a fixed-position red outline + label over
 * every DOM text node containing `needle`. Returns the number of nodes
 * highlighted so the caller can decide whether an annotated screenshot
 * is meaningful.
 */
async function annotateMatches(page: Page, needle: string): Promise<number> {
  return await page.evaluate((needle) => {
    const container = document.createElement("div");
    container.setAttribute("data-pricing-guard-overlay", "true");
    container.style.cssText =
      "position:fixed;inset:0;pointer-events:none;z-index:2147483647;";
    document.body.appendChild(container);

    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    const nodes: Text[] = [];
    let n: Node | null;
    // eslint-disable-next-line no-cond-assign
    while ((n = walker.nextNode())) {
      const t = n as Text;
      if (t.parentElement?.closest("[data-pricing-guard-overlay]")) continue;
      if (t.nodeValue && t.nodeValue.toLowerCase().includes(needle.toLowerCase())) {
        nodes.push(t);
      }
    }
    let count = 0;
    for (const node of nodes) {
      const text = node.nodeValue ?? "";
      const idx = text.toLowerCase().indexOf(needle.toLowerCase());
      if (idx === -1) continue;
      const range = document.createRange();
      range.setStart(node, idx);
      range.setEnd(node, idx + needle.length);
      const rects = Array.from(range.getClientRects());
      for (const r of rects) {
        if (r.width < 1 || r.height < 1) continue;
        const box = document.createElement("div");
        box.style.cssText = [
          "position:absolute",
          `top:${r.top + window.scrollY - 4}px`,
          `left:${r.left + window.scrollX - 4}px`,
          `width:${r.width + 8}px`,
          `height:${r.height + 8}px`,
          "border:3px solid #ff2d55",
          "border-radius:4px",
          "box-shadow:0 0 0 2px rgba(255,255,255,0.9),0 0 20px rgba(255,45,85,0.6)",
          "background:rgba(255,45,85,0.12)",
        ].join(";");
        container.appendChild(box);

        const label = document.createElement("div");
        label.textContent = `FORBIDDEN: ${needle}`;
        label.style.cssText = [
          "position:absolute",
          `top:${r.top + window.scrollY - 24}px`,
          `left:${r.left + window.scrollX - 4}px`,
          "background:#ff2d55",
          "color:#fff",
          "font:600 11px/1 -apple-system,system-ui,sans-serif",
          "padding:3px 6px",
          "border-radius:3px",
          "white-space:nowrap",
        ].join(";");
        container.appendChild(label);
        count++;
      }
    }
    return count;
  }, needle);
}

async function clearAnnotations(page: Page) {
  await page.evaluate(() => {
    document
      .querySelectorAll('[data-pricing-guard-overlay="true"]')
      .forEach((el) => el.remove());
  });
}

for (const route of ROUTES_TO_SCAN) {
  test(`no forbidden pricing on ${route}`, async ({ page }, testInfo) => {
    // Route allowlist: SEO Packages routes are permitted to render the
    // Bullets/Boom/Bombs product block. Record & skip.
    if (isSeoPackagesRoute(route)) {
      const discoveredVia: RouteReport["discoveredVia"] =
        PUBLIC_ROUTES_TO_SCAN.includes(route as (typeof PUBLIC_ROUTES_TO_SCAN)[number]) &&
        SITEMAP_ROUTES.includes(route)
          ? "both"
          : SITEMAP_ROUTES.includes(route)
            ? "sitemap"
            : "static";
      runReport.push({
        route,
        url: route,
        status: null,
        scanned: false,
        skippedReason: "SEO Packages allowlist",
        matches: [],
        discoveredVia,
      });
      test.skip(true, `${route} is in SEO_PACKAGES_ALLOWED_ROUTES`);
      return;
    }

    const response = await page.goto(route, { waitUntil: "networkidle" });
    const status = response?.status() ?? null;
    const bodyText = await page.locator("body").innerText();

    const discoveredVia: RouteReport["discoveredVia"] =
      PUBLIC_ROUTES_TO_SCAN.includes(route as (typeof PUBLIC_ROUTES_TO_SCAN)[number]) &&
      SITEMAP_ROUTES.includes(route)
        ? "both"
        : SITEMAP_ROUTES.includes(route)
          ? "sitemap"
          : "static";

    const record: RouteReport = {
      route,
      url: page.url(),
      status,
      scanned: true,
      matches: [],
      discoveredVia,
    };

    const routeSlug = route.replace(/\W+/g, "_").replace(/^_|_$/g, "") || "root";

    async function captureMatch(
      kind: "substring" | "regex",
      name: string,
      severity: Severity,
      matchedText: string,
      index: number,
    ) {
      const { contextBefore, contextAfter } = context(bodyText, index, matchedText.length);
      const fullPath = join(REPORT_DIR, `${routeSlug}_${record.matches.length}_full.png`);
      const snippetPath = join(
        REPORT_DIR,
        `${routeSlug}_${record.matches.length}_snippet.png`,
      );
      const annotatedPath = join(
        REPORT_DIR,
        `${routeSlug}_${record.matches.length}_annotated.png`,
      );
      await page.screenshot({ path: fullPath, fullPage: true }).catch(() => undefined);
      let snippetWritten: string | null = null;
      // Best-effort element screenshot of the offending text.
      try {
        const loc = page.getByText(matchedText, { exact: false }).first();
        if ((await loc.count()) > 0) {
          await loc.scrollIntoViewIfNeeded();
          await loc.screenshot({ path: snippetPath });
          snippetWritten = snippetPath;
        }
      } catch {
        snippetWritten = null;
      }
      // Annotated overlay: draw a red box + label over every occurrence
      // of the matched text, then take a full-page screenshot so a
      // reviewer can see the offending region in context.
      let annotatedWritten: string | null = null;
      try {
        const count = await annotateMatches(page, matchedText);
        if (count > 0) {
          await page.screenshot({ path: annotatedPath, fullPage: true });
          annotatedWritten = annotatedPath;
        }
        await clearAnnotations(page);
      } catch {
        annotatedWritten = null;
      }
      record.matches.push({
        kind,
        name,
        severity,
        matchedText,
        contextBefore,
        contextAfter,
        fullPageScreenshot: fullPath,
        snippetScreenshot: snippetWritten,
        annotatedScreenshot: annotatedWritten,
      });
    }

    // 1) Exact substring bans.
    for (const forbidden of FORBIDDEN_ON_TERRITORY_SURFACES) {
      const idx = bodyText.indexOf(forbidden.text);
      if (idx !== -1) {
        await captureMatch("substring", forbidden.text, forbidden.severity, forbidden.text, idx);
      }
    }

    // 2) Regex bans.
    for (const p of FORBIDDEN_PATTERNS) {
      const re = new RegExp(p.source, p.flags.includes("g") ? p.flags : p.flags + "g");
      let m: RegExpExecArray | null;
      while ((m = re.exec(bodyText)) !== null) {
        await captureMatch("regex", p.name, p.severity, m[0], m.index);
        if (m.index === re.lastIndex) re.lastIndex++;
      }
    }

    // Positive smoke assertion on `/` so a redirect or blank page can't
    // fake a pass.
    if (route === "/") {
      expect(bodyText, `Expected "${RULE_LABEL}" on ${route}`).toContain(RULE_LABEL);
    }

    runReport.push(record);

    if (record.matches.length > 0) {
      // Attach artifacts to the Playwright HTML report too.
      for (const m of record.matches) {
        await testInfo.attach(`${m.severity}:${m.name}`, {
          body: `[${m.severity}] ${m.kind} "${m.matchedText}" at …${m.contextBefore}[${m.matchedText}]${m.contextAfter}…`,
          contentType: "text/plain",
        });
        if (m.annotatedScreenshot) {
          await testInfo
            .attach(`annotated:${m.name}`, {
              path: m.annotatedScreenshot,
              contentType: "image/png",
            })
            .catch(() => undefined);
        }
      }
      const failMatches = record.matches.filter((m) => m.severity === "fail");
      const warnMatches = record.matches.filter((m) => m.severity === "warn");
      if (warnMatches.length > 0) {
        console.warn(
          `⚠️  pricing-guard warnings on ${route}: ` +
            warnMatches
              .map((m) => `[${m.kind}] ${m.name} → "${m.matchedText}"`)
              .join("; "),
        );
      }
      if (failMatches.length > 0) {
        const summary = failMatches
          .map((m) => `[${m.kind}] ${m.name} → "${m.matchedText}"`)
          .join("; ");
        throw new Error(`Forbidden pricing on ${route}: ${summary}`);
      }
    }
  });
}