import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { test, expect, type Page } from "@playwright/test";
import {
  FORBIDDEN_ON_TERRITORY_SURFACES,
  FORBIDDEN_PATTERNS,
  PUBLIC_ROUTES_TO_SCAN,
  RULE_LABEL,
  isSeoPackagesRoute,
  isSuppressed,
  REQUIRED_ON_SEO_PACKAGES,
  FORBIDDEN_ON_SEO_PACKAGES,
  type Severity,
  type RouteSuppression,
} from "../src/config/pricing";

// Whole-site sweep. Fails the build if any public route (other than
// the allowlisted SEO Packages routes in src/config/pricing.ts) leaks
// the removed Bullets/Boom/Bombs block or the $85/$285/$585 one-time
// prices. On failure, writes a diagnostic artifact under
// `pricing-guard-report/` with each URL, the exact matched text, and
// element + full-page screenshots of the offending region.
//
// The forbidden strings, regex patterns, allowed routes, and route
// list are ALL defined in src/config/pricing.ts — this spec has no
// pricing knowledge of its own.

const REPORT_DIR = join(process.cwd(), "pricing-guard-report");
const REPORT_JSON = join(REPORT_DIR, "report.json");
const REPORT_MD = join(REPORT_DIR, "report.md");
const PREVIOUS_JSON = join(REPORT_DIR, "previous.json");
const SUMMARY_JSON = join(REPORT_DIR, "summary.json");
const SITEMAP_PATH = join(process.cwd(), "public", "sitemap.xml");

/**
 * Optional baseline override for computing `isNew`. When
 * PRICING_GUARD_BASELINE_PATH points at an existing `report.json`
 * (from a prior run or a stored artifact), that file is used as the
 * baseline instead of the report we're about to overwrite.
 */
const BASELINE_PATH = process.env.PRICING_GUARD_BASELINE_PATH
  ? (process.env.PRICING_GUARD_BASELINE_PATH.startsWith("/")
      ? process.env.PRICING_GUARD_BASELINE_PATH
      : join(process.cwd(), process.env.PRICING_GUARD_BASELINE_PATH))
  : REPORT_JSON;

/**
 * True when running under GitHub Actions — enables `::error` /
 * `::warning` workflow-command output for PR annotations.
 *
 * Can be forced on/off via PRICING_GUARD_ANNOTATIONS=on|off
 * (set by the CLI's `--annotations` flag).
 */
const ANNOTATIONS_ENV = (process.env.PRICING_GUARD_ANNOTATIONS ?? "").toLowerCase();
const EMIT_GITHUB_ANNOTATIONS =
  ANNOTATIONS_ENV === "on"
    ? true
    : ANNOTATIONS_ENV === "off"
      ? false
      : process.env.GITHUB_ACTIONS === "true";

/**
 * Which mode(s) to run. Set via PRICING_GUARD_MODE=packages|territory|all
 * (defaults to "all"). Routes whose natural mode is filtered out are
 * skipped entirely.
 */
const MODE_FILTER = ((): "packages" | "territory" | "all" => {
  const v = (process.env.PRICING_GUARD_MODE ?? "all").toLowerCase();
  return v === "packages" || v === "territory" ? v : "all";
})();

/**
 * Restrict the sweep to a comma-separated list of pathnames.
 * PRICING_GUARD_ROUTES="/,/pricing,/seo-packages"
 */
const ROUTE_FILTER: string[] | null = (() => {
  const raw = process.env.PRICING_GUARD_ROUTES;
  if (!raw) return null;
  return raw
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
})();

/** Escape a value for a GitHub workflow-command parameter. */
function ghEscape(s: string): string {
  return s
    .replace(/%/g, "%25")
    .replace(/\r/g, "%0D")
    .replace(/\n/g, "%0A")
    .replace(/,/g, "%2C")
    .replace(/:/g, "%3A");
}
function ghMessageEscape(s: string): string {
  return s.replace(/%/g, "%25").replace(/\r/g, "%0D").replace(/\n/g, "%0A");
}

/**
 * Parse `public/sitemap.xml` (generated by scripts/generate-sitemap.ts
 * on every publish) and return the path portion of every entry. Falls
 * back to an empty list if the sitemap is missing or malformed, so
 * CI never dies on a bad sitemap — the static PUBLIC_ROUTES_TO_SCAN
 * list still runs.
 */
function readSitemapRoutes(): string[] {
  if (!existsSync(SITEMAP_PATH)) return [];
  try {
    const xml = readFileSync(SITEMAP_PATH, "utf8");
    const locs = Array.from(xml.matchAll(/<loc>([^<]+)<\/loc>/g), (m) => m[1]);
    const paths = new Set<string>();
    for (const loc of locs) {
      try {
        const u = new URL(loc);
        // Skip binary/static assets and anchors.
        if (/\.(xml|png|jpg|jpeg|webp|svg|pdf|zip)$/i.test(u.pathname)) continue;
        paths.add(u.pathname.replace(/\/+$/, "") || "/");
      } catch {
        /* not a URL — skip */
      }
    }
    return [...paths];
  } catch {
    return [];
  }
}

const SITEMAP_ROUTES = readSitemapRoutes();
const ALL_ROUTES = Array.from(
  new Set<string>([...PUBLIC_ROUTES_TO_SCAN, ...SITEMAP_ROUTES]),
);
const ROUTES_TO_SCAN = ALL_ROUTES.filter((route) => {
  if (ROUTE_FILTER && !ROUTE_FILTER.includes(route)) return false;
  if (MODE_FILTER === "all") return true;
  const routeMode = isSeoPackagesRoute(route) ? "packages" : "territory";
  return routeMode === MODE_FILTER;
});

type Match = {
  kind: "substring" | "regex" | "required-missing";
  name: string;
  severity: Severity;
  matchedText: string;
  contextBefore: string;
  contextAfter: string;
  fullPageScreenshot: string;
  snippetScreenshot: string | null;
  annotatedScreenshot: string | null;
  suppressedBy?: RouteSuppression;
  isNew?: boolean;
};

type RouteReport = {
  route: string;
  url: string;
  status: number | null;
  scanned: boolean;
  skippedReason?: string;
  matches: Match[];
  discoveredVia: "static" | "sitemap" | "both";
  mode: "territory" | "packages";
};

function ensureReportDir() {
  if (!existsSync(REPORT_DIR)) mkdirSync(REPORT_DIR, { recursive: true });
}

function context(text: string, index: number, len: number) {
  const before = text.slice(Math.max(0, index - 60), index);
  const after = text.slice(index + len, index + len + 60);
  return { contextBefore: before, contextAfter: after };
}

// Accumulate one report per test run.
const runReport: RouteReport[] = [];

/**
 * Load the previous run's report (if any) BEFORE we overwrite it in
 * beforeAll, so we can diff new vs. pre-existing matches. Stored as
 * `previous.json` for reference in CI artifacts.
 */
type PrevMatchKey = string;
function matchKey(route: string, m: Pick<Match, "kind" | "name" | "matchedText">): PrevMatchKey {
  return `${route}|${m.kind}|${m.name}|${m.matchedText}`;
}
const previousMatchKeys = new Set<PrevMatchKey>();
let previousLoaded = false;
function loadPreviousReport() {
  if (previousLoaded) return;
  previousLoaded = true;
  if (!existsSync(BASELINE_PATH)) return;
  try {
    const prev = JSON.parse(readFileSync(BASELINE_PATH, "utf8"));
    // Snapshot the previous run for the artifact bundle.
    writeFileSync(PREVIOUS_JSON, JSON.stringify(prev, null, 2));
    const routes: RouteReport[] = prev?.routes ?? [];
    for (const r of routes) {
      for (const m of r.matches ?? []) {
        if (m.suppressedBy) continue;
        previousMatchKeys.add(matchKey(r.route, m));
      }
    }
  } catch {
    /* previous report missing/corrupt — treat everything as new */
  }
}

test.beforeAll(() => {
  ensureReportDir();
  loadPreviousReport();
  // Reset report on first run.
  writeFileSync(REPORT_JSON, JSON.stringify({ generatedAt: null, routes: [] }, null, 2));
});

test.afterAll(() => {
  // Suppressed matches never count toward fail/warn.
  const anyFailed = runReport.some((r) =>
    r.matches.some((m) => m.severity === "fail" && !m.suppressedBy),
  );
  const anyWarned = runReport.some((r) =>
    r.matches.some((m) => m.severity === "warn" && !m.suppressedBy),
  );
  writeFileSync(
    REPORT_JSON,
    JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        ok: !anyFailed,
        anyWarned,
        sitemapRoutesFound: SITEMAP_ROUTES.length,
        totalRoutesScanned: ROUTES_TO_SCAN.length,
        routes: runReport,
      },
      null,
      2,
    ),
  );
  const md: string[] = [];
  md.push(`# Pricing guard report`);
  md.push(``);
  md.push(`- Overall: ${anyFailed ? "❌ FAIL" : anyWarned ? "⚠️  PASS (with warnings)" : "✅ PASS"}`);
  md.push(`- Routes scanned: ${runReport.filter((r) => r.scanned).length}`);
  md.push(`- Territory-mode routes: ${runReport.filter((r) => r.mode === "territory" && r.scanned).length}`);
  md.push(`- Packages-mode routes: ${runReport.filter((r) => r.mode === "packages" && r.scanned).length}`);
  md.push(`- Routes discovered via sitemap: ${SITEMAP_ROUTES.length}`);
  const suppressed = runReport.reduce(
    (n, r) => n + r.matches.filter((m) => m.suppressedBy).length,
    0,
  );
  md.push(`- Suppressed matches (per-route allowlist): ${suppressed}`);
  const newlyIntroduced = runReport.reduce(
    (n, r) => n + r.matches.filter((m) => m.isNew && !m.suppressedBy).length,
    0,
  );
  md.push(`- Newly introduced matches vs. previous run: ${newlyIntroduced}`);
  md.push(`- Filter — mode: \`${MODE_FILTER}\`, routes: \`${ROUTE_FILTER ? ROUTE_FILTER.join(",") : "*"}\`, annotations: \`${EMIT_GITHUB_ANNOTATIONS ? "on" : "off"}\``);
  md.push(``);
  for (const r of runReport) {
    if (r.matches.length === 0) continue;
    const activeMatches = r.matches.filter((m) => !m.suppressedBy);
    const fail = activeMatches.some((m) => m.severity === "fail");
    const icon = activeMatches.length === 0 ? "🟡" : fail ? "❌" : "⚠️ ";
    md.push(`## ${icon} [${r.mode}] ${r.route}`);
    md.push(``);
    md.push(`URL: \`${r.url}\``);
    md.push(``);
    for (const m of r.matches) {
      const suppressTag = m.suppressedBy ? ` (SUPPRESSED — ${m.suppressedBy.reason})` : "";
      const newTag = m.isNew && !m.suppressedBy ? " 🆕 NEW" : "";
      md.push(
        `- **[${m.severity}][${m.kind}] ${m.name}**${newTag}${suppressTag} matched \`${m.matchedText}\``,
      );
      md.push(`  - context: …${m.contextBefore}**${m.matchedText}**${m.contextAfter}…`);
      md.push(`  - full-page screenshot: \`${m.fullPageScreenshot}\``);
      if (m.snippetScreenshot) md.push(`  - snippet screenshot: \`${m.snippetScreenshot}\``);
      if (m.annotatedScreenshot) md.push(`  - annotated overlay: \`${m.annotatedScreenshot}\``);
      if (m.suppressedBy) {
        md.push(
          `  - suppressed by: ${m.suppressedBy.addedBy} on ${m.suppressedBy.addedOn}` +
            (m.suppressedBy.ref ? ` (${m.suppressedBy.ref})` : ""),
        );
      }
    }
    md.push(``);
  }
  writeFileSync(REPORT_MD, md.join("\n"));

  // Compact machine-readable summary for CI consumption.
  const totals = {
    routesScanned: runReport.filter((r) => r.scanned).length,
    routesTerritory: runReport.filter((r) => r.mode === "territory" && r.scanned).length,
    routesPackages: runReport.filter((r) => r.mode === "packages" && r.scanned).length,
    sitemapRoutesFound: SITEMAP_ROUTES.length,
    matchesTotal: runReport.reduce((n, r) => n + r.matches.length, 0),
    matchesActive: runReport.reduce(
      (n, r) => n + r.matches.filter((m) => !m.suppressedBy).length,
      0,
    ),
    matchesFail: runReport.reduce(
      (n, r) => n + r.matches.filter((m) => m.severity === "fail" && !m.suppressedBy).length,
      0,
    ),
    matchesWarn: runReport.reduce(
      (n, r) => n + r.matches.filter((m) => m.severity === "warn" && !m.suppressedBy).length,
      0,
    ),
    matchesSuppressed: runReport.reduce(
      (n, r) => n + r.matches.filter((m) => m.suppressedBy).length,
      0,
    ),
    matchesNew: runReport.reduce(
      (n, r) => n + r.matches.filter((m) => m.isNew && !m.suppressedBy).length,
      0,
    ),
    matchesNewFail: runReport.reduce(
      (n, r) =>
        n +
        r.matches.filter(
          (m) => m.isNew && !m.suppressedBy && m.severity === "fail",
        ).length,
      0,
    ),
    matchesNewWarn: runReport.reduce(
      (n, r) =>
        n +
        r.matches.filter(
          (m) => m.isNew && !m.suppressedBy && m.severity === "warn",
        ).length,
      0,
    ),
  };
  const newMatches = runReport.flatMap((r) =>
    r.matches
      .filter((m) => m.isNew && !m.suppressedBy)
      .map((m) => ({
        route: r.route,
        mode: r.mode,
        severity: m.severity,
        kind: m.kind,
        name: m.name,
        matchedText: m.matchedText,
      })),
  );
  writeFileSync(
    SUMMARY_JSON,
    JSON.stringify(
      {
        generatedAt: new Date().toISOString(),
        ok: !anyFailed,
        anyWarned,
        anyNew: totals.matchesNew > 0,
        anyNewFail: totals.matchesNewFail > 0,
        baselinePath: BASELINE_PATH,
        filter: {
          mode: MODE_FILTER,
          routes: ROUTE_FILTER,
          annotations: EMIT_GITHUB_ANNOTATIONS,
        },
        totals,
        newMatches,
      },
      null,
      2,
    ),
  );
});

/**
 * In-page highlighter: draws a fixed-position red outline + label over
 * every DOM text node containing `needle`. Returns the number of nodes
 * highlighted so the caller can decide whether an annotated screenshot
 * is meaningful.
 */
async function annotateMatches(page: Page, needle: string): Promise<number> {
  return await page.evaluate((needle) => {
    const container = document.createElement("div");
    container.setAttribute("data-pricing-guard-overlay", "true");
    container.style.cssText =
      "position:fixed;inset:0;pointer-events:none;z-index:2147483647;";
    document.body.appendChild(container);

    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    const nodes: Text[] = [];
    let n: Node | null;
    // eslint-disable-next-line no-cond-assign
    while ((n = walker.nextNode())) {
      const t = n as Text;
      if (t.parentElement?.closest("[data-pricing-guard-overlay]")) continue;
      if (t.nodeValue && t.nodeValue.toLowerCase().includes(needle.toLowerCase())) {
        nodes.push(t);
      }
    }
    let count = 0;
    for (const node of nodes) {
      const text = node.nodeValue ?? "";
      const idx = text.toLowerCase().indexOf(needle.toLowerCase());
      if (idx === -1) continue;
      const range = document.createRange();
      range.setStart(node, idx);
      range.setEnd(node, idx + needle.length);
      const rects = Array.from(range.getClientRects());
      for (const r of rects) {
        if (r.width < 1 || r.height < 1) continue;
        const box = document.createElement("div");
        box.style.cssText = [
          "position:absolute",
          `top:${r.top + window.scrollY - 4}px`,
          `left:${r.left + window.scrollX - 4}px`,
          `width:${r.width + 8}px`,
          `height:${r.height + 8}px`,
          "border:3px solid #ff2d55",
          "border-radius:4px",
          "box-shadow:0 0 0 2px rgba(255,255,255,0.9),0 0 20px rgba(255,45,85,0.6)",
          "background:rgba(255,45,85,0.12)",
        ].join(";");
        container.appendChild(box);

        const label = document.createElement("div");
        label.textContent = `FORBIDDEN: ${needle}`;
        label.style.cssText = [
          "position:absolute",
          `top:${r.top + window.scrollY - 24}px`,
          `left:${r.left + window.scrollX - 4}px`,
          "background:#ff2d55",
          "color:#fff",
          "font:600 11px/1 -apple-system,system-ui,sans-serif",
          "padding:3px 6px",
          "border-radius:3px",
          "white-space:nowrap",
        ].join(";");
        container.appendChild(label);
        count++;
      }
    }
    return count;
  }, needle);
}

async function clearAnnotations(page: Page) {
  await page.evaluate(() => {
    document
      .querySelectorAll('[data-pricing-guard-overlay="true"]')
      .forEach((el) => el.remove());
  });
}

function discoveryFor(route: string): RouteReport["discoveredVia"] {
  const inStatic = PUBLIC_ROUTES_TO_SCAN.includes(
    route as (typeof PUBLIC_ROUTES_TO_SCAN)[number],
  );
  const inSitemap = SITEMAP_ROUTES.includes(route);
  return inStatic && inSitemap ? "both" : inSitemap ? "sitemap" : "static";
}

for (const route of ROUTES_TO_SCAN) {
  const mode: "territory" | "packages" = isSeoPackagesRoute(route)
    ? "packages"
    : "territory";

  test(`pricing guard [${mode}] ${route}`, async ({ page }, testInfo) => {
    const response = await page.goto(route, { waitUntil: "networkidle" });
    const status = response?.status() ?? null;
    const bodyText = await page.locator("body").innerText();

    const record: RouteReport = {
      route,
      url: page.url(),
      status,
      scanned: true,
      matches: [],
      discoveredVia: discoveryFor(route),
      mode,
    };

    const routeSlug = route.replace(/\W+/g, "_").replace(/^_|_$/g, "") || "root";

    async function captureMatch(
      kind: "substring" | "regex" | "required-missing",
      name: string,
      severity: Severity,
      matchedText: string,
      index: number,
    ) {
      const suppressedBy = isSuppressed(route, matchedText, name) ?? undefined;
      const { contextBefore, contextAfter } = context(bodyText, index, matchedText.length);
      const fullPath = join(REPORT_DIR, `${routeSlug}_${record.matches.length}_full.png`);
      const snippetPath = join(
        REPORT_DIR,
        `${routeSlug}_${record.matches.length}_snippet.png`,
      );
      const annotatedPath = join(
        REPORT_DIR,
        `${routeSlug}_${record.matches.length}_annotated.png`,
      );
      // Skip screenshot work entirely for suppressed matches — they
      // exist only to keep the audit trail visible in the report.
      if (!suppressedBy) {
        await page.screenshot({ path: fullPath, fullPage: true }).catch(() => undefined);
      }
      let snippetWritten: string | null = null;
      // Best-effort element screenshot of the offending text.
      if (!suppressedBy) try {
        const loc = page.getByText(matchedText, { exact: false }).first();
        if ((await loc.count()) > 0) {
          await loc.scrollIntoViewIfNeeded();
          await loc.screenshot({ path: snippetPath });
          snippetWritten = snippetPath;
        }
      } catch {
        snippetWritten = null;
      }
      // Annotated overlay: draw a red box + label over every occurrence
      // of the matched text, then take a full-page screenshot so a
      // reviewer can see the offending region in context.
      let annotatedWritten: string | null = null;
      if (!suppressedBy) try {
        const count = await annotateMatches(page, matchedText);
        if (count > 0) {
          await page.screenshot({ path: annotatedPath, fullPage: true });
          annotatedWritten = annotatedPath;
        }
        await clearAnnotations(page);
      } catch {
        annotatedWritten = null;
      }
      record.matches.push({
        kind,
        name,
        severity,
        matchedText,
        contextBefore,
        contextAfter,
        fullPageScreenshot: fullPath,
        snippetScreenshot: snippetWritten,
        annotatedScreenshot: annotatedWritten,
        suppressedBy,
        isNew: !suppressedBy && !previousMatchKeys.has(matchKey(route, { kind, name, matchedText })),
      });
    }

    if (mode === "territory") {
      // -- Territory mode -----------------------------------------------
      for (const forbidden of FORBIDDEN_ON_TERRITORY_SURFACES) {
        const idx = bodyText.indexOf(forbidden.text);
        if (idx !== -1) {
          await captureMatch("substring", forbidden.text, forbidden.severity, forbidden.text, idx);
        }
      }
      for (const p of FORBIDDEN_PATTERNS) {
        const re = new RegExp(p.source, p.flags.includes("g") ? p.flags : p.flags + "g");
        let m: RegExpExecArray | null;
        while ((m = re.exec(bodyText)) !== null) {
          await captureMatch("regex", p.name, p.severity, m[0], m.index);
          if (m.index === re.lastIndex) re.lastIndex++;
        }
      }
      if (route === "/") {
        expect(bodyText, `Expected "${RULE_LABEL}" on ${route}`).toContain(RULE_LABEL);
      }
    } else {
      // -- SEO Packages mode --------------------------------------------
      // 1) Every REQUIRED string must be present — a missing one means
      //    the product block failed to render.
      for (const req of REQUIRED_ON_SEO_PACKAGES) {
        if (!bodyText.includes(req.text)) {
          await captureMatch(
            "required-missing",
            `required:${req.text}`,
            req.severity,
            req.text,
            0,
          );
        }
      }
      // 2) Territory-rule strings MUST NOT leak onto packages routes.
      for (const forbidden of FORBIDDEN_ON_SEO_PACKAGES) {
        const idx = bodyText.indexOf(forbidden.text);
        if (idx !== -1) {
          await captureMatch(
            "substring",
            `territory-leak:${forbidden.text}`,
            forbidden.severity,
            forbidden.text,
            idx,
          );
        }
      }
    }

    runReport.push(record);

    const activeMatches = record.matches.filter((m) => !m.suppressedBy);
    if (activeMatches.length > 0) {
      // Attach artifacts to the Playwright HTML report too.
      for (const m of activeMatches) {
        await testInfo.attach(`${m.severity}:${m.name}`, {
          body: `[${m.severity}] ${m.kind} "${m.matchedText}" at …${m.contextBefore}[${m.matchedText}]${m.contextAfter}…`,
          contentType: "text/plain",
        });
        if (m.annotatedScreenshot) {
          await testInfo
            .attach(`annotated:${m.name}`, {
              path: m.annotatedScreenshot,
              contentType: "image/png",
            })
            .catch(() => undefined);
        }

        // GitHub Actions PR annotations. Emitted as workflow commands
        // on stdout so they surface inline in the checks tab.
        if (EMIT_GITHUB_ANNOTATIONS) {
          const cmd = m.severity === "fail" ? "error" : "warning";
          const artifactHint = m.annotatedScreenshot
            ? ` — annotated overlay: ${m.annotatedScreenshot.replace(process.cwd() + "/", "")}`
            : m.snippetScreenshot
              ? ` — snippet: ${m.snippetScreenshot.replace(process.cwd() + "/", "")}`
              : "";
          const newTag = m.isNew ? " [NEW]" : "";
          const title = ghEscape(`[pricing-guard/${mode}]${newTag} ${route} → ${m.name}`);
          const message = ghMessageEscape(
            `${m.isNew ? "NEW " : ""}${m.kind} match "${m.matchedText}" on ${route} (${mode} mode). ` +
              `Context: …${m.contextBefore}[[${m.matchedText}]]${m.contextAfter}…${artifactHint}`,
          );
          console.log(`::${cmd} title=${title}::${message}`);
        }
      }
      const failMatches = activeMatches.filter((m) => m.severity === "fail");
      const warnMatches = activeMatches.filter((m) => m.severity === "warn");
      if (warnMatches.length > 0) {
        console.warn(
          `⚠️  pricing-guard warnings on ${route}: ` +
            warnMatches
              .map((m) => `[${m.kind}] ${m.name} → "${m.matchedText}"`)
              .join("; "),
        );
      }
      if (failMatches.length > 0) {
        const summary = failMatches
          .map((m) => `[${m.kind}] ${m.name} → "${m.matchedText}"`)
          .join("; ");
        throw new Error(`Forbidden pricing on ${route} [${mode}]: ${summary}`);
      }
    }
  });
}